datasets: 
    wikitext103: en
    chinese_documents: zh
    lawmt: en
    en_wiki: en

models:
    copyisallyouneed: 
        model_name: 
            pretrain: CopyisallyouneedPretrain
            train: Copyisallyouneed
        dataset_name: 
            pretrain: CopyisallyouneedWikitext103V2DatasetPretrain
            train: CopyisallyouneedWikitext103V2Dataset
            train_neg: CopyisallyouneedWikitext103V2DatasetNeg
    gpt2:
        model_name: GPT2Baseline
        # dataset_name: GPT2Dataset
        dataset_name: GPT2PPLDataset
    knnlm:
        model_name: KNNLMBaseline
        # dataset_name: KNNLMInferenceDataset
        dataset_name: GPT2PPLDataset


# ========= Global configuration ========== #
# root_dir: /dockerdata/johntianlan/sources/Copyisallyouneed
# root_dir: /apdcephfs/share_916081/johntianlan/copyisallyouneed
root_dir: /apdcephfs/share_916081/ponybwcao/Copyisallyouneed

# data_root_dir: /dockerdata/johntianlan/sources/Copyisallyouneed/data/wikitext103_1024
# data_root_dir: /apdcephfs/share_916081/johntianlan/copyisallyouneed/data/lawmt_1024
# data_root_dir: /apdcephfs/share_916081/johntianlan/copyisallyouneed/data/en_wiki_1024
data_root_dir: /apdcephfs/share_916081/ponybwcao/Copyisallyouneed/data/wikitext103_1024

# version: 2004
# ========= Global configuration ========== #
