datasets: 
    wikitext103: en
    wikipedia: en
    chinese_documents: zh
    lawmt: en
    en_wiki: en

models:
    copyisallyouneed: 
        model_name: 
            pretrain: CopyisallyouneedPretrain
            train: CopyisallyouneedPrefixOnly
            # train: CopyisallyouneedAllRefV2
            train_asyn: CopyisallyouneedAllRefV2Asyn
            train_pipeline: CopyisallyouneedAllRefV2Pipeline
            # train: CopyisallyouneedNegPrebatch
            test: CopyisallyouneedAllRefV2Pipeline
            # test: CopyisallyouneedNegPrebatch
            queryside: CopyisallyouneedQueryside
            baseline: Copyisallyouneed
        dataset_name: 
            wikitext103:
                pretrain: CopyisallyouneedWikitext103V2DatasetPretrain
                # train: CopyisallyouneedWikitext103V2DatasetPrebatchAllRef
                train: CopyisallyouneedWikitext103V2DatasetPrebatchAllRefAllCandidateV2
                train_asyn: CopyisallyouneedWikitext103V2DatasetPrebatchAllRefAllCandidateV2Asyn
                train_pipeline: CopyisallyouneedWikitext103V2DatasetPrebatchAllRefAllCandidateV2Asyn
                # train: CopyisallyouneedWikitext103V2DatasetNegPrebatch
                queryside: CopyisallyouneedWikitext103V2DatasetQueryside
                baseline: CopyisallyouneedWikitext103V2Dataset
                # train_neg: CopyisallyouneedWikitext103V2DatasetNeg
            wikipedia:
                train_pipeline: CopyisallyouneedWikipediaDataset
                train: CopyisallyouneedPrefixOnly
    gpt2:
        model_name: 
            train: GPT2Baseline
            test: GPT2Baseline
        # dataset_name: GPT2Dataset
        dataset_name: 
            wikitext103:
                train: GPT2Dataset
                test: GPT2Dataset
    knnlm:
        model_name: KNNLMBaseline
        # dataset_name: KNNLMInferenceDataset
        dataset_name: GPT2PPLDataset


# ========= Global configuration ========== #
# root_dir: /dockerdata/johntianlan/sources/Copyisallyouneed
# root_dir: /apdcephfs/share_916081/johntianlan/copyisallyouneed
root_dir: /apdcephfs/share_916081/shared_info/ponybwcao/Copyisallyouneed

# data_root_dir: /dockerdata/johntianlan/sources/Copyisallyouneed/data/wikitext103_1024
# data_root_dir: /apdcephfs/share_916081/johntianlan/copyisallyouneed/data/lawmt_1024
# data_root_dir: /apdcephfs/share_916081/johntianlan/copyisallyouneed/data/en_wiki_1024
data_root_dir: /apdcephfs/share_916081/shared_info/ponybwcao/Copyisallyouneed/data/wikitext103_1024
log_dir: /apdcephfs/share_916081/shared_info/ponybwcao/Copyisallyouneed/log
# version: 2004
# ========= Global configuration ========== #
